version: "3"
services:

  ##
  ## Start services required for Openblocks (MongoDB and Redis)
  ##
  mongodb:
    image: "mongo:4.4"
    container_name: mongodb
    environment:
      MONGO_INITDB_DATABASE: openblocks
      MONGO_INITDB_ROOT_USERNAME: openblocks
      MONGO_INITDB_ROOT_PASSWORD: secret123
    # Uncomment to save database data into local 'mongodata' folder
    # volumes:
    #   - ./mogodata:/data/db
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: redis


  ##
  ## Start Openblocks backend services (api-service and node-service)
  ##
  openblocks-api-service:
    image: openblocksdev/openblocks-ce-api-service:latest
    container_name: openblocks-api-service
    # Enabled ports to be able to access backend from host
    # ports:
    #   - "8080:8080"
    environment:
      PUID: "9001"
      PGID: "9001"
      MONGODB_URI: "mongodb://openblocks:secret123@mongodb/openblocks?authSource=admin"
      REDIS_URL: "redis://redis:6379"
      JS_EXECUTOR_URI: "http://openblocks-node-service:6060"
      ENABLE_USER_SIGN_UP: "true"
      ENCRYPTION_PASSWORD: "openblocks.dev"
      ENCRYPTION_SALT: "openblocks.dev"
      CORS_ALLOWED_DOMAINS: "*"
    restart: unless-stopped
    depends_on:
      - mongodb
      - redis

  openblocks-node-service:
    image: openblocksdev/openblocks-ce-node-service:latest
    container_name: openblocks-node-service
    # Enabled ports to be able to access backend from host
    # ports:
    #   - "6060:6060"
    environment:
      PUID: "9001"
      PGID: "9001"
      OPENBLOCKS_API_SERVICE_URL: "http://openblocks-api-service:8080"
    restart: unless-stopped
    depends_on:
      - openblocks-api-service

  ##
  ## Start Openblocks web frontend
  ##
  openblocks-frontend:
    image: openblocksdev/openblocks-ce-frontend:latest
    container_name: openblocks-frontend
    ports:
      - "3000:3000"
    environment:
      PUID: "9001"
      PGID: "9001"
      OPENBLOCKS_API_SERVICE_URL: "http://openblocks-api-service:8080"
      OPENBLOCKS_NODE_SERVICE_URL: "http://openblocks-node-service:6060"
    restart: unless-stopped
    depends_on:
      - openblocks-node-service
      - openblocks-api-service

