{{- $nameSpace := include "openblocks.namespace" . -}}
{{- $mongoUser := first .Values.mongodb.auth.usernames -}}
{{- $mongoPassword := first .Values.mongodb.auth.passwords -}}
{{- $mongoServicename := .Values.mongodb.service.nameOverride -}}
{{- $openblocksDatabase := first .Values.mongodb.auth.databases -}}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "openblocks.fullname" . }}-api-service
  labels:
    {{- include "openblocks.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
stringData:
  {{- if .Values.mongodb.enabled }}
  MONGODB_URI: "mongodb://{{ $mongoUser }}:{{ $mongoPassword }}@{{ $mongoServicename }}.{{ $nameSpace }}.svc.cluster.local/{{ $openblocksDatabase }}?retryWrites=true&ssl=false"
  {{- else }}
  MONGODB_URI: {{- .Values.mongodb.externalUrl | quote }}
  {{- end }}
  ENCRYPTION_PASSWORD: {{ .Values.apiService.config.encryption.password | default "openblocks.dev" | quote }}
  ENCRYPTION_SALT: {{ .Values.apiService.config.encryption.salt | default "openblocks.dev" | quote }}

