apiVersion: v2
name: openblocks
description: A Helm chart for Kubernetes for installing openblocks

type: application
# Chart version (change every time you make changes to the chart)
version: 0.1.0

# Openblocks version
appVersion: "latest"

# Dependencies needed for Openblocks deployment
dependencies:
  - condition: redis.enabled
    name: redis
    repository: https://charts.bitnami.com/bitnami
    version: 17.0.10
  - condition: mongodb.enabled
    name: mongodb
    repository: https://charts.bitnami.com/bitnami
    version: 13.6.2

